/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// English (United Kingdom)
export default {
  'fabric.atlassianSwitcher.switchTo': 'Switch to',
  'fabric.atlassianSwitcher.switchToTooltip': 'Switch to…',
  'fabric.atlassianSwitcher.recent': 'Recent',
  'fabric.atlassianSwitcher.more': 'More',
  'fabric.atlassianSwitcher.try': 'Try',
  'fabric.atlassianSwitcher.manageList': 'Manage list',
  'fabric.atlassianSwitcher.jiraProject': 'Jira project',
  'fabric.atlassianSwitcher.confluenceSpace': 'Confluence space',
  'fabric.atlassianSwitcher.administration': 'Administration',
  'fabric.atlassianSwitcher.discoverMore': 'More Atlassian products',
  'fabric.atlassianSwitcher.browseApps': 'Browse Marketplace apps',
  'fabric.atlassianSwitcher.errorHeading': 'Something’s gone wrong',
  'fabric.atlassianSwitcher.errorText':
    'We keep track of these errors, but feel free to contact us if refreshing doesn’t fix things',
  'fabric.atlassianSwitcher.errorImageAltText':
    'A broken robot and a number of people busy fixing it.',
  'fabric.atlassianSwitcher.errorTextNetwork':
    'We couldn’t load this list. Please reload the page and try again.',
  'fabric.atlassianSwitcher.errorTextLoggedOut':
    'You’ve been logged out. Please log in again.',
  'fabric.atlassianSwitcher.login': 'Log in',
  'fabric.atlassianSwitcher.show.more.sites': 'Show more sites',
  'fabric.atlassianSwitcher.discover': 'Discover',
  'fabric.atlassianSwitcher.product.description.confluence':
    'Document collaboration',
  'fabric.atlassianSwitcher.product.description.jsd':
    'IT service desk and customer service',
  'fabric.atlassianSwitcher.product.description.jsw':
    'Project and issue tracking',
  'fabric.atlassianSwitcher.product.description.opsgenie':
    'Modern incident management',
};
