/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// French
export default {
  'fabric.atlassianSwitcher.switchTo': 'Passer à',
  'fabric.atlassianSwitcher.switchToTooltip': 'Basculer vers…',
  'fabric.atlassianSwitcher.recent': 'Récents',
  'fabric.atlassianSwitcher.more': 'Plus',
  'fabric.atlassianSwitcher.try': 'Essayer',
  'fabric.atlassianSwitcher.manageList': 'Gérer la liste',
  'fabric.atlassianSwitcher.jiraProject': 'Projet Jira',
  'fabric.atlassianSwitcher.confluenceSpace': 'Espace Confluence',
  'fabric.atlassianSwitcher.administration': 'Administration',
  'fabric.atlassianSwitcher.discoverMore': 'More Atlassian products',
  'fabric.atlassianSwitcher.browseApps': 'Parcourir les apps du Marketplace',
  'fabric.atlassianSwitcher.errorHeading': 'Une erreur est survenue',
  'fabric.atlassianSwitcher.errorText':
    'Nous suivons ces erreurs, mais n’hésitez pas à nous contacter si elles persistent même après avoir actualisé la page.',
  'fabric.atlassianSwitcher.errorImageAltText':
    'Plusieurs personnes occupées à réparer un robot cassé.',
  'fabric.atlassianSwitcher.errorTextNetwork':
    'Impossible de charger la liste. Actualisez la page, puis réessayez.',
  'fabric.atlassianSwitcher.errorTextLoggedOut':
    'Vous avez été déconnecté. Veuillez vous reconnecter.',
  'fabric.atlassianSwitcher.login': 'Se connecter',
  'fabric.atlassianSwitcher.show.more.sites': 'Afficher plus de sites',
  'fabric.atlassianSwitcher.discover': 'Discover',
  'fabric.atlassianSwitcher.product.description.confluence':
    'Document collaboration',
  'fabric.atlassianSwitcher.product.description.jsd':
    'IT service desk and customer service',
  'fabric.atlassianSwitcher.product.description.jsw':
    'Project and issue tracking',
  'fabric.atlassianSwitcher.product.description.opsgenie':
    'Modern incident management',
};
