/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Portuguese (Brazil)
export default {
  'fabric.atlassianSwitcher.switchTo': 'Alternar para',
  'fabric.atlassianSwitcher.switchToTooltip': 'Alternar para…',
  'fabric.atlassianSwitcher.recent': 'Recentes',
  'fabric.atlassianSwitcher.more': 'Mais',
  'fabric.atlassianSwitcher.try': 'Testar',
  'fabric.atlassianSwitcher.manageList': 'Gerenciar lista',
  'fabric.atlassianSwitcher.jiraProject': 'Projeto do Jira',
  'fabric.atlassianSwitcher.confluenceSpace': 'Espaço do Confluence',
  'fabric.atlassianSwitcher.administration': 'Administração',
  'fabric.atlassianSwitcher.discoverMore': 'More Atlassian products',
  'fabric.atlassianSwitcher.browseApps': 'Procurar por apps do Marketplace',
  'fabric.atlassianSwitcher.errorHeading': 'Algo deu errado',
  'fabric.atlassianSwitcher.errorText':
    'Nós acompanhamos esses erros, mas fique à vontade para entrar em contato conosco caso a atualização não resolva as coisas',
  'fabric.atlassianSwitcher.errorImageAltText':
    'Um robô quebrado e várias pessoas ocupadas no conserto dele.',
  'fabric.atlassianSwitcher.errorTextNetwork':
    'Não foi possível carregar esta lista. Recarregue a página e tente novamente.',
  'fabric.atlassianSwitcher.errorTextLoggedOut':
    'Sua sessão foi encerrada. Entre novamente.',
  'fabric.atlassianSwitcher.login': 'Entrar',
  'fabric.atlassianSwitcher.show.more.sites': 'Mostrar mais sites',
  'fabric.atlassianSwitcher.discover': 'Discover',
  'fabric.atlassianSwitcher.product.description.confluence':
    'Document collaboration',
  'fabric.atlassianSwitcher.product.description.jsd':
    'IT service desk and customer service',
  'fabric.atlassianSwitcher.product.description.jsw':
    'Project and issue tracking',
  'fabric.atlassianSwitcher.product.description.opsgenie':
    'Modern incident management',
};
