/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Portuguese (Portugal)
export default {
  'fabric.atlassianSwitcher.switchTo': 'Mudar para',
  'fabric.atlassianSwitcher.switchToTooltip': 'Mudar para...',
  'fabric.atlassianSwitcher.recent': 'Recente',
  'fabric.atlassianSwitcher.more': 'Mais',
  'fabric.atlassianSwitcher.try': 'Experimente',
  'fabric.atlassianSwitcher.manageList': 'Gerir lista',
  'fabric.atlassianSwitcher.jiraProject': 'Projeto do JIRA',
  'fabric.atlassianSwitcher.confluenceSpace': 'Espaço do Confluence',
  'fabric.atlassianSwitcher.administration': 'Administração',
  'fabric.atlassianSwitcher.discoverMore': 'More Atlassian products',
  'fabric.atlassianSwitcher.browseApps': 'Procurar aplicações do Marketplace',
  'fabric.atlassianSwitcher.errorHeading': 'Ocorreu um erro',
  'fabric.atlassianSwitcher.errorText':
    'Temos conhecimento destes erros, mas contacte-nos se atualizar a página não solucionar o problema.',
  'fabric.atlassianSwitcher.errorImageAltText':
    'Um problema e várias pessoas a tentar corrigi-lo.',
  'fabric.atlassianSwitcher.errorTextNetwork':
    'Não foi possível carregar esta lista. Recarregue a página e tente novamente.',
  'fabric.atlassianSwitcher.errorTextLoggedOut':
    'A sua sessão foi encerrada. Inicie sessão novamente.',
  'fabric.atlassianSwitcher.login': 'Iniciar sessão',
  'fabric.atlassianSwitcher.show.more.sites': 'Mostrar mais sites',
  'fabric.atlassianSwitcher.discover': 'Discover',
  'fabric.atlassianSwitcher.product.description.confluence':
    'Document collaboration',
  'fabric.atlassianSwitcher.product.description.jsd':
    'IT service desk and customer service',
  'fabric.atlassianSwitcher.product.description.jsw':
    'Project and issue tracking',
  'fabric.atlassianSwitcher.product.description.opsgenie':
    'Modern incident management',
};
