/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Portuguese (Brazil)
export default {
  'fabric.elements.share.form.title': 'Compartilhar',
  'fabric.elements.share.form.send': 'Enviar',
  'fabric.elements.share.form.retry': 'Tentar novamente',
  'fabric.elements.share.form.comment.placeholder': 'Adicione uma mensagem',
  'fabric.elements.share.form.user-picker.placeholder.generic':
    'Insira nome, grupo, equipe ou e-mail',
  'fabric.elements.share.form.user-picker.placeholder.existingUserOnly':
    'Insira um nome ou uma equipe',
  'fabric.elements.share.form.user-picker.add-more': 'Insira mais itens',
  'fabric.elements.share.form.user-picker.validation.required':
    'Selecione ao menos um usuário, grupo, equipe ou e-mail.',
  'fabric.elements.share.form.user-picker.no-options.domainBasedUserOnly':
    'Você só pode convidar pessoas com endereços de e-mail {domains}. Entre em contato com o administrador do site para convidar outras pessoas.',
  'fabric.elements.share.form.user-picker.no-options.existingUserOnly':
    'Não encontramos nenhum resultado para "{inputValue}".',
  'fabric.elements.share.form.user-picker.no-options.generic':
    'Não encontramos nenhum resultado para "{inputValue}". Convide pessoas usando um endereço de e-mail.',
  'fabric.elements.share.trigger.button.icon.label':
    'Ícone de compartilhamento',
  'fabric.elements.share.trigger.button.text': 'Compartilhar',
  'fabric.elements.share.trigger.button.tooltip.text': 'Compartilhar',
  'fabric.elements.share.trigger.button.invite.text': 'Convidar',
  'fabric.elements.share.copylink.button.icon.label': 'Ícone de cópia de link',
  'fabric.elements.share.copylink.button.text': 'Copiar link',
  'fabric.elements.share.copied.to.clipboard.icon.label':
    'Ícone de sucesso da cópia de link',
  'fabric.elements.share.copied.to.clipboard.message':
    'Link copiado para a área de transferência',
  'fabric.elements.share.form.capabilities.info.message':
    'Seu convite será enviado para a aprovação de um administrador',
  'fabric.elements.share.failure.icon.label': 'Ícone de erro',
  'fabric.elements.share.failure.message': 'Não foi possível compartilhar',
  'fabric.elements.share.success.message':
    '{objeto, selecionar, blogpost {Blog post shared} painel {Board shared} calendário {Calendar shared} rascunho {Draft shared} filtro {Filter shared} item {Issue shared} mídia {Media shared} página {Page shared} projeto {Project shared} solicitação de pull {Pull Request shared} pergunta {Question shared} relatório {Report shared} repositório {Repository shared} solicitação {Request shared} roteiro {Roadmap shared} site {Site shared} espaço {Space shared} outro {Link compartilhado}}',
  'fabric.elements.share.admin.notified.message':
    'Seu administrador foi notificado',
};
