// @flow

import sinon from 'sinon';
import cases from 'jest-in-case';

import { createDateParser } from '../../date-parser';

const DATE_INVARIANT = new Date(2000, 7, 28);

cases(
  `createDateParser('en-US')(partialDateString)`,
  ({ partialDateString, date }) => {
    // Setup
    const clock = sinon.useFakeTimers(DATE_INVARIANT.getTime());

    // Assert
    expect(createDateParser('en-US')(partialDateString)).toEqual(date);

    // Teardown
    clock.restore();
  },
  [
    { name: '2', partialDateString: '2', date: new Date(2000, 1, 28) },
    { name: '2/', partialDateString: '2/', date: new Date(2000, 1, 28) },
    { name: '2/1', partialDateString: '2/1', date: new Date(2000, 1, 1) },
    { name: '2/18', partialDateString: '2/18', date: new Date(2000, 1, 18) },
    { name: '2/18/', partialDateString: '2/18/', date: new Date(2000, 1, 18) },
    {
      name: '2/18/1',
      partialDateString: '2/18/1',
      date: new Date(2001, 1, 18),
    },
    {
      name: '2/18/19',
      partialDateString: '2/18/19',
      date: new Date(2019, 1, 18),
    },
    {
      name: '2/18/199',
      partialDateString: '2/18/199',
      date: new Date(199, 1, 18),
    },
    {
      name: '2/18/1993',
      partialDateString: '2/18/1993',
      date: new Date(1993, 1, 18),
    },
  ],
);

cases(
  'createDateParser(locale)(fullDateString)',
  ({ locale, formatDateString, fullDateString, date }) => {
    // Setup
    const IntlBefore = Intl;

    // eslint-disable-next-line no-global-assign
    Intl = {
      DateTimeFormat: () => {
        return {
          format: () => formatDateString,
        };
      },
    };

    // Assert
    expect(createDateParser(locale)(fullDateString)).toEqual(date);

    // Teardown
    // eslint-disable-next-line no-global-assign
    Intl = IntlBefore;
  },
  [
    {
      name: 'ca-ES',
      locale: 'ca-ES',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'zh-TW',
      locale: 'zh-TW',
      formatDateString: '1993/2/18',
      fullDateString: '2000/8/28',
      date: DATE_INVARIANT,
    },
    {
      name: 'cs-CZ',
      locale: 'cs-CZ',
      formatDateString: '18. 2. 1993',
      fullDateString: '28. 8. 2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'da-DK',
      locale: 'da-DK',
      formatDateString: '18.2.1993',
      fullDateString: '28.8.2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'de-DE',
      locale: 'de-DE',
      formatDateString: '18.2.1993',
      fullDateString: '28.8.2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'el-GR',
      locale: 'el-GR',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'en-US',
      locale: 'en-US',
      formatDateString: '2/18/1993',
      fullDateString: '8/28/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'fi-FI',
      locale: 'fi-FI',
      formatDateString: '18.2.1993',
      fullDateString: '28.8.2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'fr-FR',
      locale: 'fr-FR',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'he-IL',
      locale: 'he-IL',
      formatDateString: '18.2.1993',
      fullDateString: '28.8.2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'hu-HU',
      locale: 'hu-HU',
      formatDateString: '1993. 02. 18.',
      fullDateString: '2000. 08. 28.',
      date: DATE_INVARIANT,
    },
    {
      name: 'is-IS',
      locale: 'is-IS',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'it-IT',
      locale: 'it-IT',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'ja-JP',
      locale: 'ja-JP',
      formatDateString: '1993/2/18',
      fullDateString: '2000/8/28',
      date: DATE_INVARIANT,
    },
    {
      name: 'ko-KR',
      locale: 'ko-KR',
      formatDateString: '1993. 2. 18.',
      fullDateString: '2000. 8. 28.',
      date: DATE_INVARIANT,
    },
    {
      name: 'nl-NL',
      locale: 'nl-NL',
      formatDateString: '18-2-1993',
      fullDateString: '28-8-2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'nb-NO',
      locale: 'nb-NO',
      formatDateString: '18.2.1993',
      fullDateString: '28.8.2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'pl-PL',
      locale: 'pl-PL',
      formatDateString: '18.02.1993',
      fullDateString: '28.08.2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'pt-BR',
      locale: 'pt-BR',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'ro-RO',
      locale: 'ro-RO',
      formatDateString: '18.02.1993',
      fullDateString: '28.08.2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'ru-RU',
      locale: 'ru-RU',
      formatDateString: '18.02.1993',
      fullDateString: '28.08.2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'hr-HR',
      locale: 'hr-HR',
      formatDateString: '18. 02. 1993.',
      fullDateString: '28. 08. 2000.',
      date: DATE_INVARIANT,
    },
    {
      name: 'sk-SK',
      locale: 'sk-SK',
      formatDateString: '18. 2. 1993',
      fullDateString: '28. 8. 2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'sq-AL',
      locale: 'sq-AL',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'sv-SE',
      locale: 'sv-SE',
      formatDateString: '1993-02-18',
      fullDateString: '2000-08-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'tr-TR',
      locale: 'tr-TR',
      formatDateString: '18.02.1993',
      fullDateString: '28.08.2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'ur-PK',
      locale: 'ur-PK',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'id-ID',
      locale: 'id-ID',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'uk-UA',
      locale: 'uk-UA',
      formatDateString: '18.02.1993',
      fullDateString: '28.08.2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'be-BY',
      locale: 'be-BY',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'sl-SI',
      locale: 'sl-SI',
      formatDateString: '18. 2. 1993',
      fullDateString: '28. 8. 2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'et-EE',
      locale: 'et-EE',
      formatDateString: '18.2.1993',
      fullDateString: '28.8.2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'lv-LV',
      locale: 'lv-LV',
      formatDateString: '1993.02.18.',
      fullDateString: '2000.08.28.',
      date: DATE_INVARIANT,
    },
    {
      name: 'lt-LT',
      locale: 'lt-LT',
      formatDateString: '1993-02-18',
      fullDateString: '2000-08-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'vi-VN',
      locale: 'vi-VN',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'hy-AM',
      locale: 'hy-AM',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'az-Latn-AZ',
      locale: 'az-Latn-AZ',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'eu-ES',
      locale: 'eu-ES',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'mk-MK',
      locale: 'mk-MK',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'af-ZA',
      locale: 'af-ZA',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'ka-GE',
      locale: 'ka-GE',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'fo-FO',
      locale: 'fo-FO',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'hi-IN',
      locale: 'hi-IN',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'ms-MY',
      locale: 'ms-MY',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'kk-KZ',
      locale: 'kk-KZ',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'ky-KG',
      locale: 'ky-KG',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'sw-KE',
      locale: 'sw-KE',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'uz-Latn-UZ',
      locale: 'uz-Latn-UZ',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'tt-RU',
      locale: 'tt-RU',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'pa-IN',
      locale: 'pa-IN',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'gu-IN',
      locale: 'gu-IN',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'ta-IN',
      locale: 'ta-IN',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'te-IN',
      locale: 'te-IN',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'kn-IN',
      locale: 'kn-IN',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'sa-IN',
      locale: 'sa-IN',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'mn-MN',
      locale: 'mn-MN',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'gl-ES',
      locale: 'gl-ES',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'kok-IN',
      locale: 'kok-IN',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'syr-SY',
      locale: 'syr-SY',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'dv-MV',
      locale: 'dv-MV',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'zh-CN',
      locale: 'zh-CN',
      formatDateString: '1993/2/18',
      fullDateString: '2000/8/28',
      date: DATE_INVARIANT,
    },
    {
      name: 'de-CH',
      locale: 'de-CH',
      formatDateString: '18.2.1993',
      fullDateString: '28.8.2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'en-GB',
      locale: 'en-GB',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-MX',
      locale: 'es-MX',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'fr-BE',
      locale: 'fr-BE',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'it-CH',
      locale: 'it-CH',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'nl-BE',
      locale: 'nl-BE',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'nn-NO',
      locale: 'nn-NO',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'pt-PT',
      locale: 'pt-PT',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'sr-Latn-CS',
      locale: 'sr-Latn-CS',
      formatDateString: '18.2.1993.',
      fullDateString: '28.8.2000.',
      date: DATE_INVARIANT,
    },
    {
      name: 'sv-FI',
      locale: 'sv-FI',
      formatDateString: '1993-02-18',
      fullDateString: '2000-08-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'az-Cyrl-AZ',
      locale: 'az-Cyrl-AZ',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'ms-BN',
      locale: 'ms-BN',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'uz-Cyrl-UZ',
      locale: 'uz-Cyrl-UZ',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'zh-HK',
      locale: 'zh-HK',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'de-AT',
      locale: 'de-AT',
      formatDateString: '18.2.1993',
      fullDateString: '28.8.2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'en-AU',
      locale: 'en-AU',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-ES',
      locale: 'es-ES',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'fr-CA',
      locale: 'fr-CA',
      formatDateString: '1993-02-18',
      fullDateString: '2000-08-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'sr-Cyrl-CS',
      locale: 'sr-Cyrl-CS',
      formatDateString: '18.2.1993.',
      fullDateString: '28.8.2000.',
      date: DATE_INVARIANT,
    },
    {
      name: 'de-LU',
      locale: 'de-LU',
      formatDateString: '18.2.1993',
      fullDateString: '28.8.2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'en-CA',
      locale: 'en-CA',
      formatDateString: '1993-02-18',
      fullDateString: '2000-08-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-GT',
      locale: 'es-GT',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'fr-CH',
      locale: 'fr-CH',
      formatDateString: '18.02.1993',
      fullDateString: '28.08.2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'zh-MO',
      locale: 'zh-MO',
      formatDateString: '1993/2/18',
      fullDateString: '2000/8/28',
      date: DATE_INVARIANT,
    },
    {
      name: 'de-LI',
      locale: 'de-LI',
      formatDateString: '18.2.1993',
      fullDateString: '28.8.2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'en-NZ',
      locale: 'en-NZ',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-CR',
      locale: 'es-CR',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'fr-LU',
      locale: 'fr-LU',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'en-IE',
      locale: 'en-IE',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-PA',
      locale: 'es-PA',
      formatDateString: '02/18/1993',
      fullDateString: '08/28/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'fr-MC',
      locale: 'fr-MC',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'en-ZA',
      locale: 'en-ZA',
      formatDateString: '1993/02/18',
      fullDateString: '2000/08/28',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-DO',
      locale: 'es-DO',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'en-JM',
      locale: 'en-JM',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-VE',
      locale: 'es-VE',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'en-029',
      locale: 'en-029',
      formatDateString: '2/18/1993',
      fullDateString: '8/28/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-CO',
      locale: 'es-CO',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'en-BZ',
      locale: 'en-BZ',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-PE',
      locale: 'es-PE',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'en-TT',
      locale: 'en-TT',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-AR',
      locale: 'es-AR',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'en-ZW',
      locale: 'en-ZW',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-EC',
      locale: 'es-EC',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'en-PH',
      locale: 'en-PH',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-CL',
      locale: 'es-CL',
      formatDateString: '18-02-1993',
      fullDateString: '28-08-2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-UY',
      locale: 'es-UY',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-PY',
      locale: 'es-PY',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-BO',
      locale: 'es-BO',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-SV',
      locale: 'es-SV',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-HN',
      locale: 'es-HN',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-NI',
      locale: 'es-NI',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'es-PR',
      locale: 'es-PR',
      formatDateString: '02/18/1993',
      fullDateString: '08/28/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'am-ET',
      locale: 'am-ET',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'tzm-Latn-DZ',
      locale: 'tzm-Latn-DZ',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'iu-Latn-CA',
      locale: 'iu-Latn-CA',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'sma-NO',
      locale: 'sma-NO',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'mn-Mong-CN',
      locale: 'mn-Mong-CN',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'gd-GB',
      locale: 'gd-GB',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'en-MY',
      locale: 'en-MY',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'prs-AF',
      locale: 'prs-AF',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'wo-SN',
      locale: 'wo-SN',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'rw-RW',
      locale: 'rw-RW',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'qut-GT',
      locale: 'qut-GT',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'sah-RU',
      locale: 'sah-RU',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'gsw-FR',
      locale: 'gsw-FR',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'co-FR',
      locale: 'co-FR',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'oc-FR',
      locale: 'oc-FR',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'mi-NZ',
      locale: 'mi-NZ',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'ga-IE',
      locale: 'ga-IE',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'se-SE',
      locale: 'se-SE',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'br-FR',
      locale: 'br-FR',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'smn-FI',
      locale: 'smn-FI',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'moh-CA',
      locale: 'moh-CA',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'arn-CL',
      locale: 'arn-CL',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'ii-CN',
      locale: 'ii-CN',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'dsb-DE',
      locale: 'dsb-DE',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'ig-NG',
      locale: 'ig-NG',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'kl-GL',
      locale: 'kl-GL',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'lb-LU',
      locale: 'lb-LU',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'ba-RU',
      locale: 'ba-RU',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'nso-ZA',
      locale: 'nso-ZA',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'quz-BO',
      locale: 'quz-BO',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'yo-NG',
      locale: 'yo-NG',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'ha-Latn-NG',
      locale: 'ha-Latn-NG',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'fil-PH',
      locale: 'fil-PH',
      formatDateString: '2/18/1993',
      fullDateString: '8/28/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'fy-NL',
      locale: 'fy-NL',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'ne-NP',
      locale: 'ne-NP',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'se-NO',
      locale: 'se-NO',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'iu-Cans-CA',
      locale: 'iu-Cans-CA',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'sr-Latn-RS',
      locale: 'sr-Latn-RS',
      formatDateString: '18.2.1993.',
      fullDateString: '28.8.2000.',
      date: DATE_INVARIANT,
    },
    {
      name: 'si-LK',
      locale: 'si-LK',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'sr-Cyrl-RS',
      locale: 'sr-Cyrl-RS',
      formatDateString: '18.2.1993.',
      fullDateString: '28.8.2000.',
      date: DATE_INVARIANT,
    },
    {
      name: 'lo-LA',
      locale: 'lo-LA',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'km-KH',
      locale: 'km-KH',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'cy-GB',
      locale: 'cy-GB',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'bo-CN',
      locale: 'bo-CN',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'sms-FI',
      locale: 'sms-FI',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'as-IN',
      locale: 'as-IN',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'ml-IN',
      locale: 'ml-IN',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'en-IN',
      locale: 'en-IN',
      formatDateString: '18/2/1993',
      fullDateString: '28/8/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'or-IN',
      locale: 'or-IN',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'tk-TM',
      locale: 'tk-TM',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'bs-Latn-BA',
      locale: 'bs-Latn-BA',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'mt-MT',
      locale: 'mt-MT',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'sr-Cyrl-ME',
      locale: 'sr-Cyrl-ME',
      formatDateString: '18.2.1993.',
      fullDateString: '28.8.2000.',
      date: DATE_INVARIANT,
    },
    {
      name: 'se-FI',
      locale: 'se-FI',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'zu-ZA',
      locale: 'zu-ZA',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'xh-ZA',
      locale: 'xh-ZA',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'tn-ZA',
      locale: 'tn-ZA',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'hsb-DE',
      locale: 'hsb-DE',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'bs-Cyrl-BA',
      locale: 'bs-Cyrl-BA',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'tg-Cyrl-TJ',
      locale: 'tg-Cyrl-TJ',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'sr-Latn-BA',
      locale: 'sr-Latn-BA',
      formatDateString: '18.2.1993.',
      fullDateString: '28.8.2000.',
      date: DATE_INVARIANT,
    },
    {
      name: 'smj-NO',
      locale: 'smj-NO',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'rm-CH',
      locale: 'rm-CH',
      formatDateString: '1993-2-18',
      fullDateString: '2000-8-28',
      date: DATE_INVARIANT,
    },
    {
      name: 'smj-SE',
      locale: 'smj-SE',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'quz-EC',
      locale: 'quz-EC',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'quz-PE',
      locale: 'quz-PE',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'hr-BA',
      locale: 'hr-BA',
      formatDateString: '18. 02. 1993.',
      fullDateString: '28. 08. 2000.',
      date: DATE_INVARIANT,
    },
    {
      name: 'sr-Latn-ME',
      locale: 'sr-Latn-ME',
      formatDateString: '18.2.1993.',
      fullDateString: '28.8.2000.',
      date: DATE_INVARIANT,
    },
    {
      name: 'sma-SE',
      locale: 'sma-SE',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'en-SG',
      locale: 'en-SG',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'ug-CN',
      locale: 'ug-CN',
      formatDateString: '18/02/1993',
      fullDateString: '28/08/2000',
      date: DATE_INVARIANT,
    },
    {
      name: 'sr-Cyrl-BA',
      locale: 'sr-Cyrl-BA',
      formatDateString: '18.2.1993.',
      fullDateString: '28.8.2000.',
      date: DATE_INVARIANT,
    },
  ],
);
